name: Build and Deploy Flutter Web to GitHub Pages

on:
  push:
    branches: [ submission ]
  pull_request:
    branches: [ submission ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.0'
        channel: 'stable'

    - name: Get dependencies
      run: |
        cd bloomie_frontend
        flutter pub get

    - name: Build web
      run: |
        cd bloomie_frontend
        flutter build web --release --web-renderer html

    - name: Deploy built files to submission branch docs folder
      run: |
        # Create docs folder and copy built web files
        mkdir -p docs
        cp -r bloomie_frontend/build/web/* docs/
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add docs/
        git commit -m "Update GitHub Pages build" -a || exit 0
        git push