name: Build and Deploy Flutter Web to GitHub Pages

on:
  push:
    branches: [ submission ]
  pull_request:
    branches: [ submission ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.5'
        channel: 'stable'

    - name: Get dependencies
      run: |
        cd bloomie_frontend
        flutter pub get

    - name: Build web
      run: |
        cd bloomie_frontend
        flutter build web --release --web-renderer html

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./bloomie_frontend/build/web
        publish_branch: gh-pages